version: '3.8'
services:
  rick-morty-nebula:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - HOSTNAME=0.0.0.0
    ports:
      - "80:3000"
    restart: always
