import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import Header from "@/components/layout/Header";
import "./globals.css";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comfortaa.className} antialiased bg-gray-50`}>
        <Header />
        <main className="container mx-auto px-4 py-8 min-h-screen">{children}</main>
      </body>
    </html>
  );
}
